title: SHC's murmur
email: h@cghuk.com
description: ''
rss_url: /pages/feed.xml
filter: category
recent_num: 20
avatar: 'https://imgur.com/a/Y6D0J'
favicon: 'http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico'
disqus: {}
permalink: '/:year/:month/:day/:title.html'
markdown: kramdown
highlighter: rouge
mathjax: disabled
sass:
  style: compressed
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
