name: SHC note
description: trivial notes on github
url: ' '
permalink: '/:year/:month/:day/:title.html'
markdown: kramdown
nav:
  - name: about
    href: /about
  - name: reference
    href: /ref
  - name: contact
    href: 'mailto:ivantheterrible@1530to1584.gov?You%20are%20ooold...'
sass:
  style: ':compressed'
excerpt_separator: <!-ex->
gems:
  - jekyll-paginate
paginate: 10
paginate_path: '/page:num/'
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      layout: post
